version: '3.8'

services:
  namenode:
    image: apache/hadoop:3
    container_name: hadoop-namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"   # HDFS Web UI
      - "9000:9000"   # HDFS RPC
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HADOOP_HOME: "/opt/hadoop"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/tmp/hadoop-root/dfs/name
      - ./data:/data
    networks:
      - hadoop-network

  datanode:
    image: apache/hadoop:3
    container_name: hadoop-datanode
    hostname: datanode
    command: ["hdfs", "datanode"]
    ports:
      - "9864:9864"   # DataNode Web UI
    environment:
      HADOOP_HOME: "/opt/hadoop"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode:/tmp/hadoop-root/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-network

  resourcemanager:
    image: apache/hadoop:3
    container_name: hadoop-resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"   # YARN Web UI
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      - hadoop-network

  nodemanager:
    image: apache/hadoop:3
    container_name: hadoop-nodemanager
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./hadoop.env
    depends_on:
      - resourcemanager
    networks:
      - hadoop-network

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop-network:
    driver: bridge
